### ISSUE TITLE
Crash when closing display server and generating an image

### ISSUE THREAD

**Issue by ISSOtm** [TheEssem/Image2Map#17]
I can run the following steps to reliably crash the server:
1. Start my X server (graphical server)
2. Start the Minecraft server (in my case, using `screen`)
3. Shut down the X server
4. Try to generate an image: [crash-2022-05-18_16.39.43-server.txt](https://github.com/TheEssem/Image2Map/files/8719268/crash-2022-05-18_16.39.43-server.txt)

Since starting the server before launching X11 works fine (both with it on and off), it appears that `image2map` detects whether a GUI is present at startup and expects it to persist if found.

**Comment by Patbox** [comment]
It's java's behaviour, can't be fixed without changing image library (through not sure if there is an alternative)

**Comment by ISSOtm** [comment]
A cursory look at [the API](https://docs.oracle.com/en/java/javase/15/docs/api/java.desktop/java/awt/Image.html#getScaledInstance(int,int,int)) indicates that a workaround just *might* be possible. Can you point me at where the `Image` is being created?
