### ISSUE TITLE
Maps that are direct edges to the image or that are not full are raised off of item frames

### ISSUE THREAD

**Issue by Hi-ImKyle** [TheEssem/Image2Map#27]
I believe this is related to just how maps are rendered, but maybe Image2Map can do something about it?
- Add a mod option to force all maps in item frames to render flat
- OR
- Add a command argument that is either `true` `false` that fills the maps to fit an entire 128x128 map by adding a background

If I am understanding it right, as long as the map is a full map, 128x128 the map will be flat, if its anything less, it becomes raised. Why, I have no idea and tbh it makes no sense.

Here is an example of the problem, using Image2Map's icon

`/image2map create 128 128 none https://media.forgecdn.net/avatars/thumbnails/295/227/64/64/637336262337165184.png`
![2023-03-10_23 08 00](https://user-images.githubusercontent.com/25551312/224444795-307dbb5c-8080-4dc0-9783-18c0208f75d6.png)

`/image2map create 127 127 none https://media.forgecdn.net/avatars/thumbnails/295/227/64/64/637336262337165184.png`
![2023-03-10_23 08 08](https://user-images.githubusercontent.com/25551312/224444839-4aeaf876-be97-4d10-a3ac-cc182812b2ee.png)

**Comment by Patbox** [comment]
That's vanilla. You can make item frame invisible if you don't want them

**Comment by Hi-ImKyle** [comment]
I'm aware it's vanilla. But I'd like to keep the frames and keep all the maps flat..
