### ISSUE TITLE
Dithering support

### ISSUE THREAD

**Issue by Setadokalo** [TheEssem/Image2Map#3]
currently Image2Map directly samples the color and finds the closest map color. This works as a naive solution, but it would look much nicer if it were to dither the color (possibly by identifying the closest colors in opposite directions in color space, then alternating between them based on a noise pattern?). I'll probably look into this tomorrow, but I thought it was worth bringing it up here before I do.

**Comment by TheEssem** [comment]
Good idea, maybe it could be added as a command parameter/option.
